### ISSUE TITLE
The lack of Requirements.txt

### ISSUE THREAD

**Issue by magical-cao** [ruizhang-ai/AutoAlign_Fully-Automatic-and-Effective-Knowledge-Graph-Alignment-enabled-by-Large-Language-Models#1]
Could you provide the python version of this project and the package it depends? Especially the version of tensorflow....

**Comment by ethanmock** [comment]
Hi,

Thanks for being interested in our work.

The requirements.txt for running our code and corresponding instructions have been added.

**Comment by magical-cao** [comment]
Thanks for the file,  your essay inspires me a lot.
