### ISSUE TITLE
Lack of code to use Claude generating matched_types.txt

### ISSUE THREAD

**Issue by edc3000** [ruizhang-ai/AutoAlign_Fully-Automatic-and-Effective-Knowledge-Graph-Alignment-enabled-by-Large-Language-Models#2]
This is a nice work that brings insight. But when I try to generate datasets, I find no code to use Claude for producing matched_types.txt. Can you open the code?

**Comment by ethanmock** [comment]
Hi, thank you for showing interest in our work. We directly input the generated prompts into the web-based Claude (https://claude.ai/chats) to obtain the matched types. You can use Claude or any other compatible large language models (LLMs).
